name: Template
description: Template project that uses theme_package

#publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+4

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  theme_package:
    path: ../
  cupertino_icons: ^1.0.0
  enum_to_string: ^1.0.13
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  flutter_modular: ^2.0.1
  font_awesome_flutter: ^8.10.0
  sqlite_package:
    path: ../sqlite_package
  sqlite_explorer:
    path: ../sqlite_explorer
  sqflite: ^1.3.2+1
  flutter_speed_dial: ^1.2.5

dependency_overrides:
  # Contains the FontAwesome-Pro icons.
  font_awesome_flutter:
    path: ../../font_awesome_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - data/
    - images/
    - languages/en.json
    - languages/es.json
